# Generated by Django 5.0.2 on 2026-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_wateralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='chapa_tx_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
