# Generated by Django 5.0.2 on 2026-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_dispute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifftier',
            options={'ordering': ['customer_class', 'min_usage']},
        ),
        migrations.AddField(
            model_name='tarifftier',
            name='customer_class',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('ORGANIZATION', 'Organization'), ('FACTORY', 'Factory'), ('GOVERNMENT', 'Government Organization'), ('PUBLIC_SERVICE', 'Public Service')], default='RESIDENT', max_length=20),
        ),
    ]
