# Generated by Django 5.0.2 on 2026-03-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='accounts.customer'),
        ),
    ]
