# Generated by Django 5.0.2 on 2026-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_alter_meter_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
