# Generated by Django 5.0.2 on 2026-04-27 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified_emailverification'),
        ('metering', '0005_maintenancetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_description', models.TextField(help_text='Where is the leak? (e.g. near the meter, street pipe, inside home)')),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField(help_text='Describe what you are observing')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DISPATCHED', 'Dispatched'), ('RESOLVED', 'Resolved')], default='SUBMITTED', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leakage_reports', to='accounts.customer')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leakage_reports', to='metering.meter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='metering_le_status_a08881_idx'), models.Index(fields=['customer', '-created_at'], name='metering_le_custome_4d5cc4_idx')],
            },
        ),
    ]
