# Generated by Django 5.0.2 on 2026-04-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0006_leakagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='metering.meter'),
        ),
    ]
