# Generated by Django 5.0.2 on 2026-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0007_alter_maintenancetask_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('MANUAL_REVIEW', 'Manual Review'), ('FIELD_TASK', 'Field Task'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
