# Generated by Django 5.0.2 on 2026-05-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0008_alter_meterreading_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
